{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "back-stage.serviceAccountName" . }}
  labels:
    {{- include "back-stage.labels" . | nindent 4 }}
{{- end }}
