apiVersion: v2
name: back-stage
description: Helm chart do Platform Engineering Center (backend + frontend)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - platform-engineering
  - internal-developer-platform
  - backstage
maintainers:
  - name: back-stage
